export const TRANSLATIONS_NO = {
    sideMenuHome:"Hjem",
    sideMenuMessages: "Meldinger",
    sideMenuShop: "Butikk",
    sideMenuReports: "Rapport",
    sideMenuSettings: "Innstillinger",
    dropdownAppsTitel: "Mine ting",
    dropdownStorageTitel: "Min lagring",
    homePageTitle: "Oversikt",
    homePageSubtitle: "Til <0>{{name}}</0>",
    addSomethingNewButtonTitle: "Legg til noe nytt",
    news: [{
        id: 1,
        newsTitle: "Tittel",
        newsSubtitle: "Lorem Ipsum er rett og slett dummytekst fra og for trykkeindustrien. Lorem Ipsum har vært bransjens standard for dummytekst helt siden 1500-tallet, da en ukjent boktrykker stokket en mengde bokstaver for å lage et prøveeksemplar av en bok.",
        newsContent: "I motsetning til hva mange tror, er ikke Lorem Ipsum bare tilfeldig tekst. Dets røtter springer helt tilbake til et stykke klassisk latinsk litteratur fra 45 år f.kr., hvilket gjør det over 2000 år gammelt. Richard McClintock - professor i latin ved Hampden-Sydney College i Virginia, USA - slo opp flere av de mer obskure latinske ordene, consectetur, fra en del av Lorem Ipsum, og fant dets utvilsomme opprinnelse gjennom å studere bruken av disse ordene i klassisk litteratur. Lorem Ipsum kommer fra seksjon 1.10.32 og 1.10.33 i \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) av Cicero, skrevet i år 45 f.kr. Boken er en avhandling om teorier rundt etikk, og var veldig populær under renessansen. Den første linjen av Lorem Ipsum er hentet fra en linje i seksjon 1.10.32.",
    }],
    formTitle: "Tittel",
    formSubtitle: "Undertittel",
    formDescription: "Beskrivelse",
    helpFiledTitle: "Hvordan kan vi hjelpe?",
    helpFieldContent: "Det er et velkjent faktum at lesere distraheres av lesbart innhold på en side når man ser på dens layout. Poenget med å bruke Lorem Ipsum er at det har en mer eller mindre normal fordeling av bokstaver i ord, i motsetning til 'Innhold her, innhold her', og gir inntrykk av å være lesbar tekst.",
    helpFieldButtonTitle: "Klikk på meg",
};